language: javascript
node_js:
  - "5.0"
  - "4.1"
  - "4.0"
  - "0.12"
  - "0.11"
  - "0.10"
before_script:
  - npm install -g gulp bower
  - npm install
script: gulp build
after_script:
  - npm run-script coveralls